name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create folder
        run: mkdir -p my-folder

      - name: Fetch LeetCode Stats (Auth Test)
        run: |
          curl 'https://leetcode.com/graphql' \
            -H 'Content-Type: application/json' \
            -H "Cookie: LEETCODE_SESSION=${{ secrets.LEETCODESESSION }}; csrftoken=${{ secrets.CSRFTOKEN }}" \
            --data-raw '{"query":"query { matchedUser(username: \"kbmagadi\") { submitStats { acSubmissionNum { difficulty count } } } }"}' \
            > my-folder/stats.json

      - name: Commit and Push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git diff --cached --quiet || git commit -m "Sync LeetCode data"
          git push
