name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install leetcode-cli
        run: npm install -g leetcode-cli

      - name: Configure LeetCode CLI
        run: |
          leetcode user -l https://leetcode.com \
            -u ${{ secrets.LEETCODESESSION }}

      - name: Create solutions folder
        run: mkdir -p my-folder

      - name: Fetch accepted submissions
        run: |
          leetcode list -ac | awk '{print $1}' | while read id; do
            leetcode show $id -gx > my-folder/$id.txt
          done

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync LeetCode submissions" || echo "No changes to commit"
          git push
